#! /bin/sh
# config script for opsi-depotserver
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule

db_title "Opsi Depotserver"

valid=false
while ! $valid ; do
	db_input high opsi/pcpatch_password1 || true
	db_input high opsi/pcpatch_password2 || true
	db_go || true
	db_get opsi/pcpatch_password1
	password="$RET"
	db_get opsi/pcpatch_password2
	confirm="$RET"
	if [ "$password" = "" -o "$password" != "$confirm" ] ; then
		db_fset opsi/pcpatch_password1 seen false
		db_fset opsi/pcpatch_password2 seen false
		db_input critical opsi/password_mismatch || true
		db_go || true
	else
		valid=true
	fi
done

db_input high opsi/configure_samba || true
db_go || true
db_input high opsi/configure_dhcpd || true
db_go || true

db_stop || true

