#! /bin/bash -e

# = = = = = = = = = = = = = = = = = = = = = = =
# =       Copyright (C) 2010 uib GmbH         =
# =           http://www.uib.de               =
# =          All rights reserved.             =
# = = = = = = = = = = = = = = = = = = = = = = =

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

. /usr/share/debconf/confmodule

VERBOSE=true
db_get opsi/configure_samba
CONFIGURE_SAMBA=$RET
db_get opsi/configure_dhcpd
CONFIGURE_DHCPD=$RET

case "$1" in
	configure)
		
		arguments=""
		if [ "$CONFIGURE_DHCPD" = "true" ]; then
			arguments="${arguments} --configure-dhcpd"
		fi
		
		if [ "$CONFIGURE_SAMBA" = "true" ]; then
			arguments="${arguments} --configure-samba"
		fi
		/usr/share/opsi/depotserver-init --init-current-config $arguments
		#--update-from
		
	;;
	
	abort-upgrade|abort-remove|abort-deconfigure)
	
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

db_stop

exit 0

